namespace MoveMentorChess.Domain;

public sealed record OpeningTrainingPosition(
    string PositionId,
    OpeningKey OpeningKey,
    OpeningLineKey OpeningLineKey,
    OpeningBranchKey? OpeningBranchKey,
    OpeningPositionKey OpeningPositionKey,
    OpeningTrainingMode Mode,
    OpeningTrainingSourceKind SourceKind,
    string Eco,
    string OpeningName,
    string Fen,
    int Ply,
    int MoveNumber,
    PlayerSide SideToMove,
    string Prompt,
    string Instruction,
    int Priority,
    RepertoireSide RepertoireSide,
    OpeningTrainingStrictness Strictness,
    string? ThemeLabel,
    string? PlayedMove,
    string? BetterMove,
    string? BetterMoveReason,
    IReadOnlyList<string> Tags,
    IReadOnlyList<OpeningTrainingMoveOption> CandidateMoves,
    IReadOnlyList<OpeningTrainingMove> Continuation,
    OpeningTrainingReference Reference,
    string? LineId = null,
    IReadOnlyList<OpeningTrainingBranch>? Branches = null,
    string? BranchSelectionSummary = null,
    OpeningCoverageSummary? CoverageSummary = null,
    OpponentReplyProfile? OpponentReplyProfile = null)
{
    public OpeningTrainingPosition(
        string positionId,
        OpeningTrainingMode mode,
        OpeningTrainingSourceKind sourceKind,
        string eco,
        string openingName,
        string fen,
        int ply,
        int moveNumber,
        PlayerSide sideToMove,
        string prompt,
        string instruction,
        int priority,
        string? themeLabel,
        string? playedMove,
        string? betterMove,
        string? betterMoveReason,
        IReadOnlyList<string> tags,
        IReadOnlyList<OpeningTrainingMoveOption> candidateMoves,
        IReadOnlyList<OpeningTrainingMove> continuation,
        OpeningTrainingReference reference,
        string? lineId = null,
        IReadOnlyList<OpeningTrainingBranch>? branches = null,
        string? branchSelectionSummary = null)
        : this(
            positionId,
            new OpeningKey($"{eco}:{openingName}"),
            lineId is null ? new OpeningLineKey(positionId) : new OpeningLineKey(lineId),
            null,
            new OpeningPositionKey(fen),
            mode,
            sourceKind,
            eco,
            openingName,
            fen,
            ply,
            moveNumber,
            sideToMove,
            prompt,
            instruction,
            priority,
            RepertoireSide.Both,
            OpeningTrainingStrictness.BookFlexible,
            themeLabel,
            playedMove,
            betterMove,
            betterMoveReason,
            tags,
            candidateMoves,
            continuation,
            reference,
            lineId,
            branches,
            branchSelectionSummary,
            null,
            null)
    {
    }
}
